-- init-h2.sql
CREATE SCHEMA IF NOT EXISTS DIGITALBANK;
CREATE SCHEMA IF NOT EXISTS DIGITALCREDIT;

CREATE TABLE IF NOT EXISTS DIGITALBANK.ACCOUNT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255),
    balance DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS DIGITALCREDIT.CREDIT_ACCOUNT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    credit_limit DECIMAL(10,2)
);